%% Code automagically generated by rise on 06-Sep-2013 13:04:55

function [RES]=balanced_growth___(y,x,ss,param,def,s0,s1)

RES=zeros(12,1);
RES( 1)=y(3)-(param(9)*param(10)*(y(3)+y(9))+(1-param(10))*(y(3)-y(9))+param(11)*(y(6)-y(12))+param(13)*x(2));
RES( 2)=(y(3)+y(9))-(param(9)*param(10)*(y(3)+2*y(9))+(1-param(10))*y(3)+param(11)*y(6)+param(13)*x(2));
RES( 3)=y(6)-((1-param(2))*(y(6)-y(12))+param(2)*(y(6)+y(12))-param(1)*(y(2)-(y(3)+y(9)))+param(14)*x(3));
RES( 4)=(y(6)+y(12))-((1-param(2))*y(6)+param(2)*(y(6)+2*y(12))-param(1)*((y(2)+y(8))-(y(3)+2*y(9)))+param(14)*x(3));
RES( 5)=y(2)-(param(5)*(y(2)-y(8))+(1-param(5))*(param(6)*y(3)+param(7)*y(6))+param(12)*x(1));
RES( 6)=(y(2)+y(8))-(param(5)*y(2)+(1-param(5))*(param(6)*(y(3)+y(9))+param(7)*(y(6)+y(12)))+param(12)*x(1));
RES( 7)=y(1)-(param(3)+400*(y(6)-(y(6)-y(12))));
RES( 8)=(y(1)+y(7))-(param(3)+400*((y(6)+y(12))-y(6)));
RES( 9)=y(4)-(param(8)+400*y(3));
RES(10)=(y(4)+y(10))-(param(8)+400*(y(3)+y(9)));
RES(11)=y(5)-(param(4)+400*y(2));
RES(12)=(y(5)+y(11))-(param(4)+400*(y(2)+y(8)));
