%% Code automagically generated by rise on 06-Sep-2013 13:04:55

function [RES]=dynamic_params___(z,x,ss,param,def,s0,s1)

RES=zeros(6,1);
RES(1)=z(5)-(param(9)*param(10)*z(1)+(1-param(10))*z(10)+param(11)*z(11)+param(13)*z(13));
RES(2)=z(8)-((1-param(2))*z(11)+param(2)*z(2)-param(1)*(z(4)-z(1))+param(14)*z(14));
RES(3)=z(4)-(param(5)*z(9)+(1-param(5))*(param(6)*z(5)+param(7)*z(8))+param(12)*z(12));
RES(4)=z(3)-(param(3)+400*(z(8)-z(11)));
RES(5)=z(6)-(param(8)+400*z(5));
RES(6)=z(7)-(param(4)+400*z(4));
