%% Code automagically generated by rise on 06-Sep-2013 13:04:56

function [G1,G2]=Endogenous_Shocks_Parameters___(y,x,ss,param,def,s0,s1)

ref_0_1_=s0==1;
ref_0_2_=s1==1;
ref_0_3_=ref_0_1_&&ref_0_2_;
ref_0_4_=if_elseif(ref_0_3_,1);
if nargout>0;
G1=sparse(6,14);
G1(1,1)=ref_0_4_*(-(param(9)*param(10)));
G1(2,1)=ref_0_4_*(-param(1));
G1(2,2)=ref_0_4_*(-param(2));
G1(2,4)=ref_0_4_*param(1);
G1(6,4)=-400*ref_0_4_;
G1(3,5)=ref_0_4_*(-((1-param(5))*param(6)));
G1(3,8)=ref_0_4_*(-((1-param(5))*param(7)));
G1(3,9)=ref_0_4_*(-param(5));
G1(1,10)=ref_0_4_*(-(1-param(10)));
G1(1,11)=ref_0_4_*(-param(11));
G1(2,11)=ref_0_4_*(-(1-param(2)));
G1(4,11)=ref_0_4_*400;
G1(3,12)=ref_0_4_*(-param(12));
G1(1,13)=ref_0_4_*(-param(13));
G1(2,14)=ref_0_4_*(-param(14));
G1(4,3)=ref_0_4_;
G1(3,4)=ref_0_4_;
G1(1,5)=ref_0_4_;
G1(5,5)=G1(6,4);
G1(5,6)=ref_0_4_;
G1(6,7)=ref_0_4_;
G1(2,8)=ref_0_4_;
G1(4,8)=G1(6,4);
if nargout>1;
G2=sparse(6,0);
end;
end;
