%% Code automagically generated by rise on 06-Sep-2013 13:04:56

function [G1]=StaticEndogenous___(y,x,ss,param,def,s0,s1)

if nargout>0;
G1=sparse(6,6);
G1(2,3)=-param(1);
G1(1,3)=1-((param(9)*param(10))+(1-param(10)));
G1(3,3)=-((1-param(5))*param(6));
G1(1,6)=-param(11);
G1(2,6)=1-((1-param(2))+param(2));
G1(3,6)=-((1-param(5))*param(7));
G1(4,1)=1;
G1(2,2)=param(1);
G1(3,2)=(1-param(5));
G1(6,2)=-400;
G1(5,3)=-400;
G1(5,4)=1;
G1(6,5)=1;
end;
