%% Code automagically generated by rise on 02-Sep-2013 14:51:52

function [RES]=balanced_growth___(y,x,ss,param,def,s0,s1)

RES=zeros(26,1);
RES( 1)=y(11)-(param(4)*y(5)^param(6)*y(2)^param(22));
RES( 2)=(y(11)+y(24))-(param(4)*(y(5)+y(18))^param(6)*(y(2)+y(15))^param(22));
RES( 3)=1-(y(8)*(y(1)+y(14))*(y(2)/(y(2)+y(15)))^param(22)/(y(6)+y(19)));
RES( 4)=1-((y(8)+y(21))*(y(1)+2*y(14))*((y(2)+y(15))/(y(2)+2*y(15)))^param(22)/(y(6)+2*y(19)));
RES( 5)=1-(param(2)*(y(2)/(y(2)+y(15)))^param(22)*((y(9)+y(22))+1-param(5)));
RES( 6)=1-(param(2)*((y(2)+y(15))/(y(2)+2*y(15)))^param(22)*((y(9)+2*y(22))+1-param(5)));
RES( 7)=y(12)-(y(13)*(y(4)-y(17))^param(1)*y(5)^(1-param(1)));
RES( 8)=(y(12)+y(25))-((y(13)+y(26))*y(4)^param(1)*(y(5)+y(18))^(1-param(1)));
RES( 9)=y(4)-((1-param(5))*(y(4)-y(17))+y(3));
RES(10)=(y(4)+y(17))-((1-param(5))*y(4)+(y(3)+y(16)));
RES(11)=y(7)-(y(11)^(1-param(1))*y(9)^param(1)*(1-param(1))^(1-param(1))*param(1)^param(1)/y(13));
RES(12)=(y(7)+y(20))-((y(11)+y(24))^(1-param(1))*(y(9)+y(22))^param(1)*(1-param(1))^(1-param(1))*param(1)^param(1)/(y(13)+y(26)));
RES(13)=(y(4)-y(17))/y(5)-(param(1)/(1-param(1))*y(11)/y(9));
RES(14)=y(4)/(y(5)+y(18))-(param(1)/(1-param(1))*(y(11)+y(24))/(y(9)+y(22)));
RES(15)=param(26)*(y(6)/def(1)-1)*y(6)/def(1)-((1-param(25))+param(25)*y(7)+param(26)*(y(1)+y(14))*(y(2)/(y(2)+y(15)))^param(22)*((y(6)+y(19))/def(1)-1)*(y(6)+y(19))/def(1)*(y(12)+y(25))/y(12));
RES(16)=param(26)*((y(6)+y(19))/def(1)-1)*(y(6)+y(19))/def(1)-((1-param(25))+param(25)*(y(7)+y(20))+param(26)*(y(1)+2*y(14))*((y(2)+y(15))/(y(2)+2*y(15)))^param(22)*((y(6)+2*y(19))/def(1)-1)*(y(6)+2*y(19))/def(1)*(y(12)+2*y(25))/(y(12)+y(25)));
RES(17)=y(2)+y(3)+param(7)-((1-0.5*param(26)*(y(6)/def(1)-1)^2)*y(12));
RES(18)=(y(2)+y(15))+(y(3)+y(16))+param(7)-((1-0.5*param(26)*((y(6)+y(19))/def(1)-1)^2)*(y(12)+y(25)));
RES(19)=y(10)-(ss(8)*(y(6)/ss(6))^param(17)*(y(12)/ss(12))^param(18));
RES(20)=(y(10)+y(23))-(ss(8)*((y(6)+y(19))/ss(6))^param(17)*((y(12)+y(25))/ss(12))^param(18));
RES(21)=y(8)-(param(28)*1+(1-param(28))*y(10));
RES(22)=(y(8)+y(21))-(param(28)*1+(1-param(28))*(y(10)+y(23)));
RES(23)=y(13)-(param(27)*((y(13)-y(26))/param(27))^param(21)*exp(param(24)*x(2)));
RES(24)=(y(13)+y(26))-(param(27)*(y(13)/param(27))^param(21)*exp(param(24)*x(2)));
RES(25)=y(1)-(param(2)*((y(1)-y(14))/param(2))^param(20)*exp(param(23)*x(1)));
RES(26)=(y(1)+y(14))-(param(2)*(y(1)/param(2))^param(20)*exp(param(23)*x(1)));
