%% Code automagically generated by rise on 02-Sep-2013 14:51:52

function [RES]=dynamic_params___(z,x,ss,param,def,s0,s1)

RES=zeros(13,1);
RES( 1)=z(16)-(param(4)*z(10)^param(6)*z(7)^param(22));
RES( 2)=1-(z(13)*z(1)*(z(7)/z(2))^param(22)/z(3));
RES( 3)=1-(param(2)*(z(7)/z(2))^param(22)*(z(4)+1-param(5)));
RES( 4)=z(17)-(z(18)*z(20)^param(1)*z(10)^(1-param(1)));
RES( 5)=z(9)-((1-param(5))*z(20)+z(8));
RES( 6)=z(12)-(z(16)^(1-param(1))*z(14)^param(1)*(1-param(1))^(1-param(1))*param(1)^param(1)/z(18));
RES( 7)=z(20)/z(10)-(param(1)/(1-param(1))*z(16)/z(14));
RES( 8)=param(26)*(z(11)/(param(16))-1)*z(11)/(param(16))-((1-param(25))+param(25)*z(12)+param(26)*z(1)*(z(7)/z(2))^param(22)*(z(3)/(param(16))-1)*z(3)/(param(16))*z(5)/z(17));
RES( 9)=z(7)+z(8)+param(7)-((1-0.5*param(26)*(z(11)/(param(16))-1)^2)*z(17));
RES(10)=z(15)-(ss(8)*(z(11)/ss(6))^param(17)*(z(17)/ss(12))^param(18));
RES(11)=z(13)-(param(28)*1+(1-param(28))*z(15));
RES(12)=z(18)-(param(27)*(z(21)/param(27))^param(21)*exp(param(24)*z(23)));
RES(13)=z(6)-(param(2)*(z(19)/param(2))^param(20)*exp(param(23)*z(22)));
