%% Code automagically generated by rise on 02-Sep-2013 14:51:52

function [Q,retcode]=transition_matrix___(y,x,ss,param,def,s0,s1)

retcode=0;
Q=zeros(2,2);
Q(1,1)=1-(param(29));
Q(2,1)=param(30);
Q(1,2)=param(29);
Q(2,2)=1-(param(30));
if any(isnan(Q(:))) || any(Q(:)<0) || any(Q(:)>1);
Q=[];
retcode=3;
end;
