function [ys_, params, info] = constant_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(9)=(params(8)-1)/params(8);
    ys_(7)=params(12);
    ys_(5)=params(4);
    ys_(10)=1/ys_(5)-1+params(5);
    ys_(13)=params(19);
    ys_(4)=max(1,ys_(13));
    ys_(6)=ys_(5)*ys_(4);
    ys_(1)=(ys_(9)*ys_(7)/(ys_(10)^params(6)*(1-params(6))^(1-params(6))*params(6)^params(6)))^(1/(1-params(6)));
    ys_(8)=(ys_(1)/(params(1)*((ys_(10)*(1-params(6))/params(6)/ys_(1))^params(6)/ys_(7))^params(2)*(1-params(18)-params(5)/ys_(7)*(ys_(1)*params(6)/(1-params(6))/ys_(10))^(1-params(6)))^params(3)))^(1/(params(2)+params(3)));
    ys_(2)=(ys_(10)*(1-params(6))/params(6)/ys_(1))^params(6)/ys_(7)*ys_(8);
    ys_(11)=params(5)/ys_(7)*(ys_(1)*params(6)/(1-params(6))/ys_(10))^(1-params(6))*ys_(8);
    ys_(12)=ys_(1)*params(6)/(1-params(6))/ys_(10)*ys_(2);
    ys_(3)=(1-params(18)-params(5)/ys_(7)*(ys_(1)*params(6)/(1-params(6))/ys_(10))^(1-params(6)))*ys_(8);
    % Auxiliary equations
    check_=0;
end
