%% Code automagically generated by rise on 20-Aug-2013 15:52:36

function [G1]=Parameters___(y,x,ss,param,def,s0,s1)

ref_0_1_=0.5*param(5);
ref_0_2_=y(3)-1;
ref_0_3_=ref_0_2_^2;
ref_0_5_=1-(ref_0_1_*ref_0_3_);
ref_0_9_=y(1)-1;
ref_0_12_=1-(ref_0_1_*ref_0_9_^2);
ref_0_16_=(exp(param(6))*(ref_0_12_*y(2)))*y(1);
ref_0_33_=(y(6)/ss(2))^param(9);
ref_0_34_=y(3)/ss(1);
ref_0_37_=ref_0_34_^((1-param(9))*param(8));
ref_0_40_=exp((param(10)*x(1)));
if nargout>0;
G1=sparse(3,7);
G1(1,1)=-(((ref_0_5_*y(5))*y(4))/ref_0_16_);
G1(2,1)=(((ref_0_5_*param(5))*ref_0_9_)*y(1))/ref_0_12_;
G1(2,2)=-1+(ref_0_5_*y(5));
G1(1,3)=-((((((param(3)*(-(0.5*ref_0_3_)))*y(5))*y(4))*ref_0_16_)-(((exp(param(6))*((-(0.5*ref_0_9_^2))*y(2)))*y(1))*(((ref_0_5_*param(3))*y(5))*y(4))))/ref_0_16_^2);
G1(2,3)=((((((ref_0_9_*((ref_0_5_*param(3))+((param(3)*param(5))*(-(0.5*ref_0_3_)))))*y(1))*ref_0_12_)-(((((param(3)*param(5))*ref_0_5_)*ref_0_9_)*y(1))*(-(0.5*ref_0_9_^2))))/ref_0_12_^2)+((param(4)*(-(0.5*ref_0_3_)))*y(5)))-(ref_0_2_*y(3));
G1(1,4)=-((-(ref_0_16_*(((ref_0_5_*param(3))*y(5))*y(4))))/ref_0_16_^2);
G1(3,5)=ref_0_40_*(((log(ref_0_34_)*(1-param(9)))*ref_0_37_)*ref_0_33_);
G1(3,6)=ref_0_40_*(((log((y(6)/ss(2)))*ref_0_33_)*ref_0_37_)+(((log(ref_0_34_)*(-param(8)))*ref_0_37_)*ref_0_33_));
G1(3,7)=(ref_0_40_*x(1))*(ref_0_33_*ref_0_37_);
end;
