%% Code automagically generated by rise on 20-Aug-2013 15:52:36

function [y]=steady_state_model___(y,x,ss,param,def,s0,s1)

y=zeros(3,1);
y(1)=1;
y(3)=(param(4)-1)/param(4);
y(2)=exp(param(7))/param(3)*y(1);
