%  DATE2SERIAL Convert date representations to serial dates.
% 
%  [s, frequency] = date2serial(dat, silent) converts the input date
%  representations dat to serial dates. The output 's' is an array of
%  serial dates corresponding to the input dat. The 'frequency' output
%  indicates the frequency of the dates.
% 
%  Inputs:
%  - dat: Date representations. It can be either an array of doubles
%  representing undated or non-dated values, a character array or cell
%  array of date strings, or objects generated by functions such as
%  rd (daily data), rw (weekly data), rm (monthly data), rq (quarterly
%  data), rh (half-yearly data), ra (annual data), or ry (yearly data).
%  - silent (optional): Boolean indicating whether to suppress error
%  messages (default is false).
% 
%  Outputs:
%  - s: Array of serial dates corresponding to the input date
%  representations. The size of 's' is the same as the size of 'dat'.
%  - frequency: Frequency of the dates. It can take the following values:
%  'U' (undated/non-dated), 'D' (daily), 'W' (weekly), 'M' (monthly),
%  'Q' (quarterly), 'H' (half-yearly), 'Y' (yearly), or 'A' (annual).
% 
%  Examples:
%  - Serial dates from a numeric range:
%  test = (date2serial(1990):date2serial(1995));
%  serial2date(test)
%  - Serial dates from a character range:
%  test = (date2serial('1990'):date2serial('1995'));
%  serial2date(test)
%  - Serial dates from a half-yearly range:
%  test = (date2serial('1990h1'):date2serial('1995h2'));
%  serial2date(test)
%  - Serial dates from a quarterly range:
%  test = (date2serial('1990q1'):date2serial('1995q4'));
%  serial2date(test)
%  - Serial dates from a monthly range:
%  test = (date2serial('1990m1'):date2serial('1995m6'));
%  serial2date(test)
%