%  rseries time series (alias for ts)
% 
%  methods
%  --------
% 
%  - [acos](rseries/acos)
%  - [acosh](rseries/acosh)
%  - [acot](rseries/acot)
%  - [acoth](rseries/acoth)
%  - [aggregate](rseries/aggregate)
%  - [allmean](rseries/allmean)
%  - [and](rseries/and)
%  - [apply](rseries/apply)
%  - [asin](rseries/asin)
%  - [asinh](rseries/asinh)
%  - [atan](rseries/atan)
%  - [atanh](rseries/atanh)
%  - [automatic_model_selection](rseries/automatic_model_selection)
%  - [bar](rseries/bar)
%  - [barh](rseries/barh)
%  - [boxplot](rseries/boxplot)
%  - [bsxfun](rseries/bsxfun)
%  - [cat](rseries/cat)
%  - [collect](rseries/collect)
%  - [corr](rseries/corr)
%  - [corrcoef](rseries/corrcoef)
%  - [cos](rseries/cos)
%  - [cosh](rseries/cosh)
%  - [cot](rseries/cot)
%  - [coth](rseries/coth)
%  - [cov](rseries/cov)
%  - [ctranspose](rseries/ctranspose)
%  - [cumprod](rseries/cumprod)
%  - [cumsum](rseries/cumsum)
%  - [decompose_series](rseries/decompose_series)
%  - [describe](rseries/describe)
%  - [display](rseries/display)
%  - [double](rseries/double)
%  - [drop](rseries/drop)
%  - [dummy](rseries/dummy)
%  - [eq](rseries/eq)
%  - [exp](rseries/exp)
%  - [expanding](rseries/expanding)
%  - [fanchart](rseries/fanchart)
%  - [ge](rseries/ge)
%  - [get](rseries/get)
%  - [gt](rseries/gt)
%  - [head](rseries/head)
%  - [hist](rseries/hist)
%  - [horzcat](rseries/horzcat)
%  - [hpfilter](rseries/hpfilter)
%  - [index](rseries/index)
%  - [interpolate](rseries/interpolate)
%  - [intersect](rseries/intersect)
%  - [isfinite](rseries/isfinite)
%  - [isinf](rseries/isinf)
%  - [isnan](rseries/isnan)
%  - [jbtest](rseries/jbtest)
%  - [kurtosis](rseries/kurtosis)
%  - [le](rseries/le)
%  - [log](rseries/log)
%  - [lt](rseries/lt)
%  - [max](rseries/max)
%  - [mean](rseries/mean)
%  - [median](rseries/median)
%  - [min](rseries/min)
%  - [minus](rseries/minus)
%  - [mode](rseries/mode)
%  - [mpower](rseries/mpower)
%  - [mrdivide](rseries/mrdivide)
%  - [mtimes](rseries/mtimes)
%  - [nan](rseries/nan)
%  - [ne](rseries/ne)
%  - [numel](rseries/numel)
%  - [ones](rseries/ones)
%  - [pages2struct](rseries/pages2struct)
%  - [plot](rseries/plot)
%  - [plotyy](rseries/plotyy)
%  - [plus](rseries/plus)
%  - [power](rseries/power)
%  - [quantile](rseries/quantile)
%  - [rand](rseries/rand)
%  - [randn](rseries/randn)
%  - [range](rseries/range)
%  - [rdivide](rseries/rdivide)
%  - [regress](rseries/regress)
%  - [rolling](rseries/rolling)
%  - [rseries](rseries/rseries)
%  - [sin](rseries/sin)
%  - [sinh](rseries/sinh)
%  - [skewness](rseries/skewness)
%  - [sort](rseries/sort)
%  - [spectrum](rseries/spectrum)
%  - [std](rseries/std)
%  - [step_dummy](rseries/step_dummy)
%  - [subsasgn](rseries/subsasgn)
%  - [subsref](rseries/subsref)
%  - [sum](rseries/sum)
%  - [tail](rseries/tail)
%  - [times](rseries/times)
%  - [transform](rseries/transform)
%  - [transpose](rseries/transpose)
%  - [uminus](rseries/uminus)
%  - [values](rseries/values)
%  - [var](rseries/var)
%  - [zeros](rseries/zeros)
% 
%  properties
%  -----------
% 
%  - [varnames] -
%  - [start] -
%  - [finish] -
%  - [frequency] -
%  - [NumberOfObservations] -
%  - [NumberOfPages] -
%  - [NumberOfVariables] -
%
%    Reference page in Doc Center
%       doc rseries
%
%