%% Code automagically generated by rise on 04-Sep-2013 09:46:37

function [RES]=dynamic___(z,x,ss,param,def,s0,s1)

RES=zeros(13,1);
RES( 1)=z(16)-(param(4)*z(10)^param(6)*z(7)^param(19));
RES( 2)=1-(z(13)*z(1)*(z(7)/z(2))^param(19)/z(3));
RES( 3)=1-(param(2)*(z(7)/z(2))^param(19)*(z(4)+1-param(5)));
RES( 4)=z(17)-(z(18)*z(20)^param(1)*z(10)^(1-param(1)));
RES( 5)=z(9)-((1-param(5))*z(20)+z(8));
RES( 6)=z(12)-(z(16)^(1-param(1))*z(14)^param(1)*(1-param(1))^(1-param(1))*param(1)^param(1)/z(18));
RES( 7)=z(20)/z(10)-(param(1)/(1-param(1))*z(16)/z(14));
RES( 8)=param(23)*(z(11)/def(1)-1)*z(11)/def(1)-((1-param(22))+param(22)*z(12)+param(23)*z(1)*(z(7)/z(2))^param(19)*(z(3)/def(1)-1)*z(3)/def(1)*z(5)/z(17));
RES( 9)=z(7)+z(8)+param(7)-((1-0.5*param(23)*(z(11)/def(1)-1)^2)*z(17));
RES(10)=z(15)-(ss(8)*(z(11)/ss(6))^param(14)*(z(17)/ss(12))^param(15));
RES(11)=z(13)-(z(15));
RES(12)=z(18)-(param(24)*(z(21)/param(24))^param(18)*exp(param(21)*z(23)));
RES(13)=z(6)-(param(2)*(z(19)/param(2))^param(17)*exp(param(20)*z(22)));
