%% Code automagically generated by rise on 04-Sep-2013 09:46:38

function [G1]=Parameters___(y,x,ss,param,def,s0,s1)

ref_0_3_=y(7)^param(19);
ref_0_7_=y(7)/y(2);
ref_0_8_=ref_0_7_^param(19);
ref_0_19_=1-param(1);
ref_0_42_=(y(11)/param(13))-1;
ref_0_76_=y(21)/param(24);
ref_0_80_=exp((param(21)*x(2)));
ref_0_83_=y(19)/param(2);
ref_0_87_=exp((param(20)*x(1)));
if nargout>0;
G1=sparse(13,17);
G1(4,1)=-((((log(y(20))*y(20)^param(1))*y(18))*y(10)^ref_0_19_)+((y(10)^ref_0_19_*(-log(y(10))))*(y(20)^param(1)*y(18))));
G1(6,1)=-(((param(1)^param(1)*((ref_0_19_^ref_0_19_*(((y(16)^ref_0_19_*(-log(y(16))))*y(14)^param(1))+((log(y(14))*y(14)^param(1))*y(16)^ref_0_19_)))+((y(16)^ref_0_19_*y(14)^param(1))*((ref_0_19_^ref_0_19_*(-log(ref_0_19_)))+(ref_0_19_^(ref_0_19_-1)*(-ref_0_19_))))))+(((y(16)^ref_0_19_*y(14)^param(1))*ref_0_19_^ref_0_19_)*((log(param(1))*param(1)^param(1))+(param(1)^(param(1)-1)*param(1)))))/y(18));
G1(7,1)=-((((ref_0_19_-(-param(1)))/ref_0_19_^2)*y(16))/y(14));
G1(3,2)=-(ref_0_8_*((1+y(4))-param(5)));
G1(13,2)=-(ref_0_87_*((((((-y(19))/param(2)^2)*param(17))*ref_0_83_^(param(17)-1))*param(2))+ref_0_83_^param(17)));
G1(1,3)=-(y(10)^param(6)*ref_0_3_);
G1(1,5)=-(((log(y(10))*y(10)^param(6))*param(4))*ref_0_3_);
ref_1_166_=param(13)^2;
G1(8,7)=(((((((-y(11))/ref_1_166_)*param(23))*y(11))*param(13))-((ref_0_42_*param(23))*y(11)))/ref_1_166_)-(((((((((-y(3))/ref_1_166_)*((param(23)*y(1))*ref_0_8_))*y(3))*param(13))-((((param(23)*y(1))*ref_0_8_)*((y(3)/param(13))-1))*y(3)))/ref_1_166_)*y(5))/y(17));
G1(9,7)=-((-(((2*((-y(11))/ref_1_166_))*ref_0_42_^1)*(0.5*param(23))))*y(17));
G1(10,8)=-(((log((y(11)/ss(6)))*(y(11)/ss(6))^param(14))*ss(8))*(y(17)/ss(12))^param(15));
G1(10,9)=-((log((y(17)/ss(12)))*(y(17)/ss(12))^param(15))*((y(11)/ss(6))^param(14)*ss(8)));
G1(13,10)=-(ref_0_87_*((log(ref_0_83_)*ref_0_83_^param(17))*param(2)));
G1(12,11)=-(ref_0_80_*((log(ref_0_76_)*ref_0_76_^param(18))*param(24)));
G1(1,12)=-((log(y(7))*ref_0_3_)*(y(10)^param(6)*param(4)));
G1(2,12)=-(((log(ref_0_7_)*ref_0_8_)*(y(13)*y(1)))/y(3));
G1(3,12)=-(((log(ref_0_7_)*ref_0_8_)*param(2))*((1+y(4))-param(5)));
G1(8,12)=-(((((((log(ref_0_7_)*ref_0_8_)*(param(23)*y(1)))*((y(3)/param(13))-1))*y(3))/param(13))*y(5))/y(17));
G1(13,13)=-((ref_0_87_*x(1))*(ref_0_83_^param(17)*param(2)));
G1(12,14)=-((ref_0_80_*x(2))*(ref_0_76_^param(18)*param(24)));
G1(8,15)=-(-1+y(12));
G1(8,16)=((ref_0_42_*y(11))/param(13))-((((((ref_0_8_*y(1))*((y(3)/param(13))-1))*y(3))/param(13))*y(5))/y(17));
G1(9,16)=-((-(0.5*ref_0_42_^2))*y(17));
G1(12,17)=-(ref_0_80_*((((((-y(21))/param(24)^2)*param(18))*ref_0_76_^(param(18)-1))*param(24))+ref_0_76_^param(18)));
G1(3,4)=(ref_0_8_*param(2));
G1(5,4)=y(20);
G1(9,6)=1;
end;
