%% Code automagically generated by rise on 04-Sep-2013 09:46:37

function [RES]=static___(y,x,ss,param,def,s0,s1)

RES=zeros(13,1);
RES( 1)=y(11)-(param(4)*y(5)^param(6)*y(2)^param(19));
RES( 2)=1-(y(8)*y(1)*(y(2)/y(2))^param(19)/y(6));
RES( 3)=1-(param(2)*(y(2)/y(2))^param(19)*(y(9)+1-param(5)));
RES( 4)=y(12)-(y(13)*y(4)^param(1)*y(5)^(1-param(1)));
RES( 5)=y(4)-((1-param(5))*y(4)+y(3));
RES( 6)=y(7)-(y(11)^(1-param(1))*y(9)^param(1)*(1-param(1))^(1-param(1))*param(1)^param(1)/y(13));
RES( 7)=y(4)/y(5)-(param(1)/(1-param(1))*y(11)/y(9));
RES( 8)=param(23)*(y(6)/def(1)-1)*y(6)/def(1)-((1-param(22))+param(22)*y(7)+param(23)*y(1)*(y(2)/y(2))^param(19)*(y(6)/def(1)-1)*y(6)/def(1)*y(12)/y(12));
RES( 9)=y(2)+y(3)+param(7)-((1-0.5*param(23)*(y(6)/def(1)-1)^2)*y(12));
RES(10)=y(10)-(ss(8)*(y(6)/ss(6))^param(14)*(y(12)/ss(12))^param(15));
RES(11)=y(8)-(y(10));
RES(12)=y(13)-(param(24)*(y(13)/param(24))^param(18)*exp(param(21)*x(2)));
RES(13)=y(1)-(param(2)*(y(1)/param(2))^param(17)*exp(param(20)*x(1)));
