%% Code automagically generated by rise on 14-Aug-2013 12:04:43

function [G1]=StaticEndogenous___(y,x,ss,param,def,s0,s1)

ref_0_1_=0.5*param(3);
ref_0_2_=y(1)-1;
ref_0_3_=ref_0_2_^2;
ref_0_4_=ref_0_1_*ref_0_3_;
ref_0_5_=1-ref_0_4_;
ref_0_12_=(exp(param(4))*(ref_0_5_*y(3)))*y(1);
ref_0_28_=y(2)/ss(2);
if nargout>0;
G1=sparse(3,3);
ref_1_43_=-((2*ref_0_2_^1)*ref_0_1_);
G1(1,1)=-((((((param(1)*ref_1_43_)*y(3))*y(2))*ref_0_12_)-((((ref_0_5_*param(1))*y(3))*y(2))*(((exp(param(4))*(ref_1_43_*y(3)))*y(1))+(exp(param(4))*(ref_0_5_*y(3))))))/ref_0_12_^2);
G1(2,1)=((((ref_0_5_*((((((param(1)*param(3))*ref_1_43_)*ref_0_2_)+((param(1)*param(3))*ref_0_5_))*y(1))+(((param(1)*param(3))*ref_0_5_)*ref_0_2_)))-(((((param(1)*param(3))*ref_0_5_)*ref_0_2_)*y(1))*ref_1_43_))/ref_0_5_^2)+((param(2)*ref_1_43_)*y(3)))-((param(3)*y(1))+(ref_0_2_*param(3)));
G1(3,1)=exp((param(8)*x(1)))*((((1/ss(1))*((1-param(7))*param(6)))*(y(1)/ss(1))^(((1-param(7))*param(6))-1))*ref_0_28_^param(7));
G1(1,2)=-(((ref_0_5_*param(1))*y(3))/ref_0_12_);
G1(3,2)=(exp((param(8)*x(1)))*((((1/ss(2))*param(7))*ref_0_28_^(param(7)-1))*(y(1)/ss(1))^((1-param(7))*param(6))))-(1/ss(2));
G1(1,3)=-(((((ref_0_5_*param(1))*y(2))*ref_0_12_)-(((exp(param(4))*ref_0_5_)*y(1))*(((ref_0_5_*param(1))*y(3))*y(2))))/ref_0_12_^2);
G1(2,3)=(ref_0_5_*param(2));
end;
