%% Code automagically generated by rise on 14-Aug-2013 12:04:43

function [RES]=vectorized_dynamic___(z,x,ss,param,def,s0,s1)

RES=zeros(3,7);
RES(1,:)=1-param(1).*(1-.5.*param(3).*(z(3,:)-1).^2).*z(5,:).*z(4,:)./((1-.5.*param(3).*(z(1,:)-1).^2).*z(2,:).*exp(param(4)).*z(1,:));
RES(2,:)=1-param(2)+param(2).*(1-.5.*param(3).*(z(3,:)-1).^2).*z(5,:)+param(1).*param(3).*(1-.5.*param(3).*(z(3,:)-1).^2).*(z(1,:)-1).*z(1,:)./(1-.5.*param(3).*(z(1,:)-1).^2)-param(3).*(z(3,:)-1).*z(3,:);
RES(3,:)=(z(6,:)./ss(2)).^param(7).*(z(3,:)./ss(1)).^((1-param(7)).*param(6)).*exp(param(8).*z(7,:))-z(4,:)./ss(2);
