%%%%%%%%%%%%%%%%%%%%   path: examples\MarkovSwitching\RamirezWaggonerZha2012   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help examples\MarkovSwitching\RamirezWaggonerZha2012\frwz_nk_dynare">examples\MarkovSwitching\RamirezWaggonerZha2012\frwz_nk_dynare</a>                              - (No help available)
%   <a href="matlab:help examples\MarkovSwitching\RamirezWaggonerZha2012\frwz_nk_dynare_dynamic">examples\MarkovSwitching\RamirezWaggonerZha2012\frwz_nk_dynare_dynamic</a>                      - (No help available)
%   <a href="matlab:help examples\MarkovSwitching\RamirezWaggonerZha2012\frwz_nk_dynare_set_auxiliary_variables">examples\MarkovSwitching\RamirezWaggonerZha2012\frwz_nk_dynare_set_auxiliary_variables</a>      - (No help available)
%   <a href="matlab:help examples\MarkovSwitching\RamirezWaggonerZha2012\frwz_nk_dynare_static">examples\MarkovSwitching\RamirezWaggonerZha2012\frwz_nk_dynare_static</a>                       - (No help available)
%   <a href="matlab:help examples\MarkovSwitching\RamirezWaggonerZha2012\frwz_nk_dynare_steadystate2">examples\MarkovSwitching\RamirezWaggonerZha2012\frwz_nk_dynare_steadystate2</a>                 -  state generated by Dynare preprocessor
%   <a href="matlab:help examples\MarkovSwitching\RamirezWaggonerZha2012\frwz_nk_test_derivs">examples\MarkovSwitching\RamirezWaggonerZha2012\frwz_nk_test_derivs</a>                         - %
%   examples\MarkovSwitching\RamirezWaggonerZha2012\functional_iteration_convergence_conditions - (No help available)
%   <a href="matlab:help examples\MarkovSwitching\RamirezWaggonerZha2012\howto">examples\MarkovSwitching\RamirezWaggonerZha2012\howto</a>                                       - % Housekeeping
%   <a href="matlab:help examples\MarkovSwitching\RamirezWaggonerZha2012\howto_frwz_nk">examples\MarkovSwitching\RamirezWaggonerZha2012\howto_frwz_nk</a>                               - % Housekeeping
%   <a href="matlab:help examples\MarkovSwitching\RamirezWaggonerZha2012\rwz_steady_state">examples\MarkovSwitching\RamirezWaggonerZha2012\rwz_steady_state</a>                            - unction [params,ss,retcode,imposed]=rwz_steady_state(params,flag)%param_struct=struct(parlist,parvals)
