function [ys_, params, info] = frwz_nk_dynare_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(1)=1;
    ys_(2)=(params(2)-1)/params(2);
    ys_(3)=ys_(1)*exp(params(5))/params(1);
    % Auxiliary equations
    check_=0;
end
