%%%%%%%%%%%%%%%%%%%%   path: examples\MarkovSwitching\GavinKeenRichterThrockmorton   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help examples\MarkovSwitching\GavinKeenRichterThrockmorton\constant">examples\MarkovSwitching\GavinKeenRichterThrockmorton\constant</a>                         - (No help available)
%   <a href="matlab:help examples\MarkovSwitching\GavinKeenRichterThrockmorton\constant_dynamic">examples\MarkovSwitching\GavinKeenRichterThrockmorton\constant_dynamic</a>                 - (No help available)
%   <a href="matlab:help examples\MarkovSwitching\GavinKeenRichterThrockmorton\constant_set_auxiliary_variables">examples\MarkovSwitching\GavinKeenRichterThrockmorton\constant_set_auxiliary_variables</a> - (No help available)
%   <a href="matlab:help examples\MarkovSwitching\GavinKeenRichterThrockmorton\constant_static">examples\MarkovSwitching\GavinKeenRichterThrockmorton\constant_static</a>                  - (No help available)
%   <a href="matlab:help examples\MarkovSwitching\GavinKeenRichterThrockmorton\constant_steadystate2">examples\MarkovSwitching\GavinKeenRichterThrockmorton\constant_steadystate2</a>            -  state generated by Dynare preprocessor
%   <a href="matlab:help examples\MarkovSwitching\GavinKeenRichterThrockmorton\howto">examples\MarkovSwitching\GavinKeenRichterThrockmorton\howto</a>                            - % housekeeping
%   <a href="matlab:help examples\MarkovSwitching\GavinKeenRichterThrockmorton\planar_diff">examples\MarkovSwitching\GavinKeenRichterThrockmorton\planar_diff</a>                      - Current=cell(2,incmnt); % 1- indexes, 2-pointers
%   <a href="matlab:help examples\MarkovSwitching\GavinKeenRichterThrockmorton\stoch_simul____">examples\MarkovSwitching\GavinKeenRichterThrockmorton\stoch_simul____</a>                  - should also allow for passing options
