%%%%%%%%%%%%%%%%%%%%   path: examples\MarkovSwitching\BiTraum2013   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help examples\MarkovSwitching\BiTraum2013\Untitled5">examples\MarkovSwitching\BiTraum2013\Untitled5</a>               - percent sign','%'
%   examples\MarkovSwitching\BiTraum2013\all_items               - (No help available)
%   examples\MarkovSwitching\BiTraum2013\bi_traum_13_ssfile      - (No help available)
%   <a href="matlab:help examples\MarkovSwitching\BiTraum2013\bt_ssfile">examples\MarkovSwitching\BiTraum2013\bt_ssfile</a>               - Instruct RISE not to bother checking that this is the true steady state
%   <a href="matlab:help examples\MarkovSwitching\BiTraum2013\dynamic_derivatives">examples\MarkovSwitching\BiTraum2013\dynamic_derivatives</a>     - anonymous function for checking validity
%   <a href="matlab:help examples\MarkovSwitching\BiTraum2013\endo_exo">examples\MarkovSwitching\BiTraum2013\endo_exo</a>                - % Code automagically generated by rise on 13-Jul-2013 13:47:20
%   <a href="matlab:help examples\MarkovSwitching\BiTraum2013\finding_bounds_for_rise">examples\MarkovSwitching\BiTraum2013\finding_bounds_for_rise</a> - % housekeeping
%   <a href="matlab:help examples\MarkovSwitching\BiTraum2013\first_order_solver">examples\MarkovSwitching\BiTraum2013\first_order_solver</a>      -  options are 0 or 'msre_klein' (for constant-parameter models)
%   <a href="matlab:help examples\MarkovSwitching\BiTraum2013\junk_print">examples\MarkovSwitching\BiTraum2013\junk_print</a>              - prototype{3}=vi.obj.ncalls;
%   <a href="matlab:help examples\MarkovSwitching\BiTraum2013\msre_filter_kim_nelson">examples\MarkovSwitching\BiTraum2013\msre_filter_kim_nelson</a>  - this filter assumes a state space of the form
%   <a href="matlab:help examples\MarkovSwitching\BiTraum2013\my_print">examples\MarkovSwitching\BiTraum2013\my_print</a>                - min_ncount) % minimum number of occurrences at which substitution occurs
%   <a href="matlab:help examples\MarkovSwitching\BiTraum2013\myderivs">examples\MarkovSwitching\BiTraum2013\myderivs</a>                - % Code automagically generated by rise on 27-Jul-2013 21:50:07
%   <a href="matlab:help examples\MarkovSwitching\BiTraum2013\parse_declaration">examples\MarkovSwitching\BiTraum2013\parse_declaration</a>       - classdef parse_declaration < handle
%   <a href="matlab:help examples\MarkovSwitching\BiTraum2013\planner_stuff">examples\MarkovSwitching\BiTraum2013\planner_stuff</a>           - % Code automagically generated by rise on 14-Jul-2013 07:13:15
%   <a href="matlab:help examples\MarkovSwitching\BiTraum2013\simulate_second_order">examples\MarkovSwitching\BiTraum2013\simulate_second_order</a>   - Q=solution.Q;
%   <a href="matlab:help examples\MarkovSwitching\BiTraum2013\state_matrices">examples\MarkovSwitching\BiTraum2013\state_matrices</a>          - examples of calls:
%   <a href="matlab:help examples\MarkovSwitching\BiTraum2013\taoMacProblem">examples\MarkovSwitching\BiTraum2013\taoMacProblem</a>           - housekeeping
%   <a href="matlab:help examples\MarkovSwitching\BiTraum2013\transit_matrix">examples\MarkovSwitching\BiTraum2013\transit_matrix</a>          - % Code automagically generated by rise on 05-Jul-2013 10:50:41
%   <a href="matlab:help examples\MarkovSwitching\BiTraum2013\transition_matrix">examples\MarkovSwitching\BiTraum2013\transition_matrix</a>       - % Code automagically generated by rise on 21-Jul-2013 16:12:48
