%% Code automagically generated by rise on 05-Jul-2013 10:50:41

function [G0]=transit_matrix(y,x,ss,param,def,s0,s1)

if nargout>0;
G0=sparse(4,4);
ref_0_1=1-param(2);
ref_0_2=1-param(3);
ref_0_3=1-param(14);
ref_0_4=1-param(15);
G0(1,1)=ref_0_1*ref_0_3;
G0(1,2)=ref_0_1*param(14);
G0(1,3)=ref_0_3*param(2);
G0(1,4)=param(2)*param(14);
G0(2,1)=ref_0_1*param(15);
G0(2,2)=ref_0_1*ref_0_4;
G0(2,3)=param(2)*param(15);
G0(2,4)=ref_0_4*param(2);
G0(3,1)=ref_0_3*param(3);
G0(3,2)=param(3)*param(14);
G0(3,3)=ref_0_2*ref_0_3;
G0(3,4)=ref_0_2*param(14);
G0(4,1)=param(3)*param(15);
G0(4,2)=ref_0_4*param(3);
G0(4,3)=ref_0_2*param(15);
G0(4,4)=ref_0_2*ref_0_4;
end;
