%% Code automagically generated by rise on 05-Jan-2013 01:28:39

function [RES]=balanced_growth(y,x,param,ss,def)

RES=zeros(16,1);
RES( 1)=1/y(3)-(y(2)*(1+(y(8)+y(16))-(y(4)+y(12)))/(y(3)+y(11)));
RES( 2)=1/(y(3)+y(11))-((y(2)+y(10))*(1+(y(8)+2*y(16))-(y(4)+2*y(12)))/(y(3)+2*y(11)));
RES( 3)=y(3)+y(6)-(y(1)*(y(6)-y(14))^param(1)*y(5)^(1-param(1))+(1-y(4))*(y(6)-y(14)));
RES( 4)=(y(3)+y(11))+(y(6)+y(14))-((y(1)+y(9))*y(6)^param(1)*(y(5)+y(13))^(1-param(1))+(1-(y(4)+y(12)))*y(6));
RES( 5)=(1-param(1))*y(1)*((y(6)-y(14))/y(5))^param(1)/y(3)-(y(7)/(1-y(5)));
RES( 6)=(1-param(1))*(y(1)+y(9))*(y(6)/(y(5)+y(13)))^param(1)/(y(3)+y(11))-((y(7)+y(15))/(1-(y(5)+y(13))));
RES( 7)=y(8)-(param(1)*y(1)*((y(6)-y(14))/y(5))^(param(1)-1));
RES( 8)=(y(8)+y(16))-(param(1)*(y(1)+y(9))*(y(6)/(y(5)+y(13)))^(param(1)-1));
RES( 9)=log(y(1))-(param(5)*log((y(1)-y(9)))+param(9)*x(1));
RES(10)=log((y(1)+y(9)))-(param(5)*log(y(1))+param(9)*x(1));
RES(11)=log(y(2)/param(2))-(param(6)*log((y(2)-y(10))/param(2))+param(10)*x(2));
RES(12)=log((y(2)+y(10))/param(2))-(param(6)*log(y(2)/param(2))+param(10)*x(2));
RES(13)=log(y(4)/param(3))-(param(7)*log((y(4)-y(12))/param(3))+param(11)*x(3));
RES(14)=log((y(4)+y(12))/param(3))-(param(7)*log(y(4)/param(3))+param(11)*x(3));
RES(15)=log(y(7)/param(4))-(param(8)*log((y(7)-y(15))/param(4))+param(12)*x(4));
RES(16)=log((y(7)+y(15))/param(4))-(param(8)*log(y(7)/param(4))+param(12)*x(4));
