%% Code automagically generated by rise on 05-Jan-2013 01:28:39

function [Jac_]=param_derivatives(y,x,param,ss,def)

Jac_=zeros(8,12);
bigi_=speye(12);
indx_2_=1;
Jac_(2,indx_2_)=-(((((bigi_(1,indx_2_).*log(y(15))).*(y(15).^param(1))).*y(4)).*(y(8).^(1-param(1))))+((((-bigi_(1,indx_2_)).*log(y(8))).*(y(8).^(1-param(1)))).*(y(4).*(y(15).^param(1)))));
ref_21_=y(15)./y(8);
Jac_(3,indx_3_)=(((((-bigi_(1,indx_3_)).*y(4)).*(ref_21_.^param(1)))+(((bigi_(1,indx_3_).*log(ref_21_)).*(ref_21_.^param(1))).*((1-param(1)).*y(4)))).*y(6))./(y(6).^2);
Jac_(4,indx_4_)=-(((bigi_(1,indx_4_).*y(4)).*(ref_21_.^(param(1)-1)))+(((bigi_(1,indx_4_).*log(ref_21_)).*(ref_21_.^(param(1)-1))).*(param(1).*y(4))));
indx_5_=[5,9];
Jac_(5,indx_5_)=-((bigi_(5,indx_5_).*log(y(12)))+(bigi_(9,indx_5_).*x(1)));
indx_6_=[2,6,10];
Jac_(6,indx_6_)=(((-(bigi_(2,indx_6_).*y(5)))./(param(2).^2))./(y(5)./param(2)))-(((bigi_(6,indx_6_).*log((y(13)./param(2))))+((((-(bigi_(2,indx_6_).*y(13)))./(param(2).^2))./(y(13)./param(2))).*param(6)))+(bigi_(10,indx_6_).*x(2)));
indx_7_=[3,7,11];
Jac_(7,indx_7_)=(((-(bigi_(3,indx_7_).*y(7)))./(param(3).^2))./(y(7)./param(3)))-(((bigi_(7,indx_7_).*log((y(14)./param(3))))+((((-(bigi_(3,indx_7_).*y(14)))./(param(3).^2))./(y(14)./param(3))).*param(7)))+(bigi_(11,indx_7_).*x(3)));
indx_8_=[4,8,12];
Jac_(8,indx_8_)=(((-(bigi_(4,indx_8_).*y(10)))./(param(4).^2))./(y(10)./param(4)))-(((bigi_(8,indx_8_).*log((y(16)./param(4))))+((((-(bigi_(4,indx_8_).*y(16)))./(param(4).^2))./(y(16)./param(4))).*param(8)))+(bigi_(12,indx_8_).*x(4)));
