%% Code automagically generated by rise on 05-Jan-2013 01:28:39

function [RES]=static(y,x,param,ss,def)

RES=zeros(8,1);
RES(1)=1/y(3)-(y(2)*(1+y(8)-y(4))/y(3));
RES(2)=y(3)+y(6)-(y(1)*y(6)^param(1)*y(5)^(1-param(1))+(1-y(4))*y(6));
RES(3)=(1-param(1))*y(1)*(y(6)/y(5))^param(1)/y(3)-(y(7)/(1-y(5)));
RES(4)=y(8)-(param(1)*y(1)*(y(6)/y(5))^(param(1)-1));
RES(5)=log(y(1))-(param(5)*log(y(1))+param(9)*x(1));
RES(6)=log(y(2)/param(2))-(param(6)*log(y(2)/param(2))+param(10)*x(2));
RES(7)=log(y(4)/param(3))-(param(7)*log(y(4)/param(3))+param(11)*x(3));
RES(8)=log(y(7)/param(4))-(param(8)*log(y(7)/param(4))+param(12)*x(4));
