%% Code automagically generated by rise on 05-Jan-2013 01:28:39

function [Jac_]=static_model_derivatives(y,x,param,ss,def)

Jac_=zeros(8,8);
bigi_=speye(8);
indx_1_=[2,3,4,8];
ref_3_=y(3).^2;
Jac_(1,indx_1_)=((-bigi_(3,indx_1_))./ref_3_)-(((((bigi_(2,indx_1_).*((1+y(8))-y(4)))+((bigi_(8,indx_1_)-bigi_(4,indx_1_)).*y(2))).*y(3))-(bigi_(3,indx_1_).*(y(2).*((1+y(8))-y(4)))))./ref_3_);
indx_2_=[1,3,4,5,6];
ref_22_=param(1)-1;
ref_27_=1-param(1);
Jac_(2,indx_2_)=(bigi_(3,indx_2_)+bigi_(6,indx_2_))-(((((bigi_(1,indx_2_).*(y(6).^param(1)))+(((param(1).*bigi_(6,indx_2_)).*(y(6).^ref_22_)).*y(1))).*(y(5).^ref_27_))+(((ref_27_.*bigi_(5,indx_2_)).*(y(5).^(ref_27_-1))).*(y(1).*(y(6).^param(1)))))+(((-bigi_(4,indx_2_)).*y(6))+(bigi_(6,indx_2_).*(1-y(4)))));
indx_3_=[1,3,5,6,7];
ref_46_=y(6)./y(5);
Jac_(3,indx_3_)=((((((bigi_(1,indx_3_).*ref_27_).*(ref_46_.^param(1)))+(((param(1).*(((bigi_(6,indx_3_).*y(5))-(bigi_(5,indx_3_).*y(6)))./(y(5).^2))).*(ref_46_.^ref_22_)).*(ref_27_.*y(1)))).*y(3))-(bigi_(3,indx_3_).*((ref_27_.*y(1)).*(ref_46_.^param(1)))))./ref_3_)-(((bigi_(7,indx_3_).*(1-y(5)))-((-bigi_(5,indx_3_)).*y(7)))./((1-y(5)).^2));
indx_4_=[1,5,6,8];
Jac_(4,indx_4_)=bigi_(8,indx_4_)-(((bigi_(1,indx_4_).*param(1)).*(ref_46_.^ref_22_))+(((ref_22_.*(((bigi_(6,indx_4_).*y(5))-(bigi_(5,indx_4_).*y(6)))./(y(5).^2))).*(ref_46_.^(ref_22_-1))).*(param(1).*y(1))));
indx_5_=1;
Jac_(5,indx_5_)=(bigi_(1,indx_5_)./y(1))-((bigi_(1,indx_5_)./y(1)).*param(5));
indx_6_=2;
Jac_(6,indx_6_)=(((bigi_(2,indx_6_).*param(2))./(param(2).^2))./(y(2)./param(2)))-((((bigi_(2,indx_6_).*param(2))./(param(2).^2))./(y(2)./param(2))).*param(6));
indx_7_=4;
Jac_(7,indx_7_)=(((bigi_(4,indx_7_).*param(3))./(param(3).^2))./(y(4)./param(3)))-((((bigi_(4,indx_7_).*param(3))./(param(3).^2))./(y(4)./param(3))).*param(7));
indx_8_=7;
Jac_(8,indx_8_)=(((bigi_(7,indx_8_).*param(4))./(param(4).^2))./(y(7)./param(4)))-((((bigi_(7,indx_8_).*param(4))./(param(4).^2))./(y(7)./param(4))).*param(8));
