%% Code automagically generated by rise on 05-Jan-2013 01:28:39

function [y]=steady_state_model(y,x,param,ss,def)

y=zeros(8,1);
y(1)=1;
y(2)=param(2);
y(4)=param(3);
y(7)=param(4);
y(3)=0.6;
y(6)=2.0;
y(5)=.31;
y(8)=.04;
