%% Code automagically generated by rise on 05-Jan-2013 01:28:39

function [Q,retcode]=transition_matrix(y,x,param,ss,def)

retcode=0;
Q=1;
Qi=zeros(1);
Qi(1,1)=1-sum(Qi(1,:));
Q=kron(Q,Qi);
if any(any(isnan(Q))) || any(any(Q<0)) || any(any(Q>1));
Q=[];
retcode=3;
end;
