%% Code automagically generated by rise on 05-Jan-2013 01:28:39

function [RES]=vectorized_dynamic_params(param,z,ss)

RES=zeros(8,12);
RES(1,:)=1./z(6,:)-(z(5,:).*(1+z(3,:)-z(2,:))./z(1,:));
RES(2,:)=z(6,:)+z(9,:)-(z(4,:).*z(15,:).^param(1,:).*z(8,:).^(1-param(1,:))+(1-z(7,:)).*z(15,:));
RES(3,:)=(1-param(1,:)).*z(4,:).*(z(15,:)./z(8,:)).^param(1,:)./z(6,:)-(z(10,:)./(1-z(8,:)));
RES(4,:)=z(11,:)-(param(1,:).*z(4,:).*(z(15,:)./z(8,:)).^(param(1,:)-1));
RES(5,:)=log(z(4,:))-(param(5,:).*log(z(12,:))+param(9,:).*z(17,:));
RES(6,:)=log(z(5,:)./param(2,:))-(param(6,:).*log(z(13,:)./param(2,:))+param(10,:).*z(18,:));
RES(7,:)=log(z(7,:)./param(3,:))-(param(7,:).*log(z(14,:)./param(3,:))+param(11,:).*z(19,:));
RES(8,:)=log(z(10,:)./param(4,:))-(param(8,:).*log(z(16,:)./param(4,:))+param(12,:).*z(20,:));
