function val=get_default_optimization_option(opt)
default_optim=struct('solver',0,...
    'explosion_limit',1e+8,...
    'Penalty',1e+8,...
    'qz_criterium',1.000001,...
    'lc_reconvexify',false,...
    'lc_algorithm','short',...
    'accelerate_solver',true,...
    'filtering_algorithm','lwz',...
    'harvey_scale_factor',[],...
    'diffuse_all',false,...
    'presample',0,...
    'kalman_tol',1.0000e-020,...
    'Hypothesis',0,...
    'verbose',false,...
    'TolFun',sqrt(eps),...
    'MaxNodes',20,...
    'MaxFunEvals',inf,...
    'UseParallel','always',...
    'Display','iter',...
    'MaxIter',1000,...
    'MaxTime',3600);
% lc_reconvexify:
% If set to true, this options treats the loose commitment
% problem as an "average" of discretion and commitment. When set
% to false, it solves the loose commitment problem as described
% in Debortoli, Maih and Nunes(2010). This option has no impact on the
% solution when the probability of commitment is either 1 or 0
val=default_optim.(opt);
